spring:
  application:
    name: ecommerce-analytics-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_analytics?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    template:
      exchange: ecommerce.product.exchange
      routing-key: ecommerce.product.routing-key

server:
  port: 8083

ecommerce:
  jwt:
    secret: secret_key_for_ecommerce_microservices_2026_at_least_64_characters_long_for_hs512
    expiration: 86400000 # 24h

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

queue:
  name: ecommerce.product.queue

